Módulo: Preguntas Frecuentes
Saca-la-Bici/app-ios pull request #17
Opened 2024-10-02 03:46 UTC by DiegoGarciaPadilla

# Descripción

Se implementaron los siguientes casos de uso.

38. Registrar pregunta frecuente (MVP)
39. Modificar pregunta frecuente (MVP)
40. Eliminar pregunta frecuente

### Comentario sobre el PR.

Para evitar los conflictos en las pruebas, realicé merge de `release/0.2` a esta rama, es por eso el número tan largo de commits.

# Conclusiones

Personalmente considero que la planeación del módulo estuvo mal, debido a las siguientes razones:

- No existe una historia de usuario para "Consultar preguntas frecuentes".
- La estimación de cada historia de usuario era de 1 punto, dando un total de 3 por todo el módulo. Considero que cada una de estas historias de usuario (incluyendo la faltante de "Consultar preguntas frecuentes", deberían ser de 3 puntos cada una (a excepción de eliminar, que probablemente sea de puntuación 1).

2024-10-02 19:31 UTC, Jesus0204 requested changes
En casos de exito todo jala bien, pero si el servidor está caído por ejemplo, no se muestra ninguna notificación de que algo fallo. 

Si puedes por favor checar esto. Muchas gracias

2024-10-02 22:18 UTC, DiegoGarciaPadilla commented
Realicé los cambios mencionados.

![image](https://github.com/user-attachments/assets/800b2cee-3c6a-46fd-98ad-ab18177c2bed)

2024-10-03 00:14 UTC, Jesus0204 requested changes
Las alertas de registrar, modificar y eliminar ya jalan exitosamente. Pero no se informa al usuario al consultar si hay un error. 

Para que por favor cambies eso :)

2024-10-03 00:53 UTC, DiegoGarciaPadilla commented
Ahora se notifica al usuario si la consulta falla.

### Caso 1: Falla al consultar preguntas frecuentes.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/fb18e64b-b0f6-4cec-84cf-f7e4cd24439c">

### Caso 2: Falla al consultar pregunta individual.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/3867361b-02a7-419c-a8d4-b17759f792ae">

2024-10-03 01:18 UTC, Jesus0204 approved these changes
Se aplicaron todos los cambios pedidos. Se puede hacer merge a release :)

2024-10-03 01:19 UTC, merged