Feature/0.1.1/consultar anuncio
Saca-la-Bici/app-ios pull request #3
Opened 2024-09-23 15:36 UTC by MariaJoseGaytan

tienen que poner esto es su código del back en el app.js:
app.listen(3000, '0.0.0.0', () => {
console.log('Server running on all network interfaces');
});

y en xcode ponen la ip de su compu.

no olviden poner el archivo de google info

Consultar anuncios
Registrar anuncios
Eliminar anuncios
Modificar anuncios

2024-09-23 16:46 UTC, DiegoGarciaPadilla requested changes
Cuando el anuncio se modifica y se dejan los cambios vacíos, no me deja modificar, sin embargo no da ninguna retroalimentación al usuario y por lo que parece que el botón no realiza ninguna acción.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/dc756b3f-9cf4-4fcb-ad73-5eaa5edb020b">

2024-09-24 03:47 UTC, MariaJoseGaytan commented
Ya fueron puestas los mensajes de error tanto para modificar como para registrar un anuncio

2024-09-24 04:12 UTC, DiegoGarciaPadilla approved these changes
'APPROVE' performed by Xcode.

2024-09-24 04:21 UTC, Jesus0204 approved these changes
También se realizaron las pruebas y todo funciona bien

2024-09-24 04:48 UTC, merged