Iniciar Sesión y Registrar Cuenta con Correo y Google
Saca-la-Bici/app-ios pull request #4
Opened 2024-09-23 16:02 UTC by Jesus0204

Se agregan las siguientes HU:

Iniciar Sesión
Cerrar Sesión
Registrar Cuenta con Correo
Registrar Cuenta con Google

2024-09-23 18:41 UTC, DiegoGarciaPadilla requested changes
Nombre no válido cuando hay espacios.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/40a40e1b-0970-4dc6-be58-69f24302ae28">

Contraseña correcta marcada como no válida.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/2efcfaa7-2053-4338-b173-e2f58e22a7a6">

2024-09-23 19:58 UTC, Jesus0204 commented
Ya fueron corregidos ambos errores, y se mejoro un aspecto de la interfaz

2024-09-24 16:30 UTC, DiegoGarciaPadilla requested changes
Cuando se intenta iniciar sesión con username falla.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/f66376c5-9d13-47b2-99bb-3de9c2fd7998">

2024-09-24 16:52 UTC, DiegoGarciaPadilla approved these changes

2024-09-24 17:01 UTC, merged